import { ResumeData, Translation, Language } from './types';

// GLOBAL AD CONFIGURATION
// Set to 'true' to show ad placeholders.
// Set to 'false' to hide all ad spaces and collapse their layout containers.
export const SHOW_ADS = true;

export const INITIAL_RESUME_STATE: ResumeData = {
  templateId: 'modern',
  personalInfo: {
    fullName: '',
    email: '',
    phone: '',
    location: '',
    website: '',
    summary: '',
    title: '',
  },
  experience: [],
  education: [],
  skills: [],
};

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    metaTitle: 'Free Resume Builder | No Signup, Private & ATS Friendly',
    metaDesc: 'Build a professional resume in minutes with HiResume. 100% free, no login required. Export to PDF, Word (DOCX) & LaTeX. Your data stays on your device.',
    metaKeywords: 'resume builder, free cv maker, no signup resume, pdf resume, latex resume, ats friendly, privacy focused resume, offline resume builder',
    nav: {
      brand: 'HiResume',
      create: 'Edit Resume',
      preview: 'Preview',
      features: 'Features',
      builder: 'Go to Builder',
    },
    landing: {
      heroTitle: 'The Only Privacy-First Free Resume Builder',
      heroSubtitle: 'Build a job-winning resume in minutes. No account needed. No tracking. No paywalls. Your data never leaves your browser.',
      cta: 'Build My Resume',
      ctaSecondary: 'View Templates',
      trustedBy: 'Used by candidates hired at top companies',
      stats: { users: '100% Free', downloads: 'PDF & LaTeX', cost: 'Privacy First' },
      howItWorksTitle: 'How to Build a Resume in 3 Steps',
      howItWorksSteps: [
        { title: 'Choose a Template', desc: 'Select from 6+ professional, ATS-optimized layouts designed for clarity.' },
        { title: 'Enter Your Details', desc: 'Fill in your experience and skills. Everything is saved automatically to your device.' },
        { title: 'Download & Apply', desc: 'Export instantly as a high-quality PDF, Word, or LaTeX file.' }
      ],
      templatesTitle: 'Professional Templates for Every Career',
      templatesDesc: 'Clean, modern, and designed to pass Applicant Tracking Systems (ATS).',
      featuresTitle: 'Why Top Candidates Choose HiResume',
      feature1Title: 'Zero Data Collection',
      feature1Desc: 'We don\'t want your data. Unlike other builders, your personal info is stored locally in your browser (LocalStorage). It never hits our servers.',
      feature2Title: '100% ATS Friendly',
      feature2Desc: 'Our templates are coded to be easily parsed by recruitment software, ensuring your resume actually reaches a human recruiter.',
      feature3Title: 'Free Exports',
      feature3Desc: 'Most builders charge for high-quality downloads. We give you standard PDF, DOCX, and source LaTeX code completely free.',
      seoTitle: 'Why Use a No-Signup Resume Builder?',
      seoContent: 'In today\'s job market, speed and privacy are essential. Traditional resume builders force you to create accounts, spam your email, and often hold your data hostage behind a paywall. HiResume changes that. We offer a completely client-side experience using Next.js technology. This means you get the speed of a web app with the security of a desktop application. Whether you need a Student CV, an Executive Resume, or a Creative Portfolio, our tool adapts to your needs without tracking your every move.',
      faqTitle: 'Frequently Asked Questions',
      faqItems: [
        { q: 'Is this resume builder truly free?', a: 'Yes. We monetize via non-intrusive ads so we never have to charge you or sell your data.' },
        { q: 'Will my employer see my resume?', a: 'No. Your data is stored only on your specific device. We cannot see, share, or sell your resume.' },
        { q: 'What is an ATS friendly resume?', a: 'ATS (Applicant Tracking Systems) are robots that read resumes before humans do. Our templates use standard formatting that these robots can easily read.' }
      ]
    },
    footer: {
      copyright: '© 2026 HiResume. All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      contact: 'Contact Us',
      faq: 'FAQ',
      disclaimer: 'Supported by privacy-respecting ad placements.',
    },
    legal: {
      privacyTitle: 'Privacy Policy',
      privacyContent: [
        'At HiResume, we prioritize your privacy. This document outlines how we handle your data.',
        '1. Data Collection: We do not collect, store, or transmit your personal resume data to any server. All inputs are stored locally in your browser\'s LocalStorage.',
        '2. Cookies & Advertising: We use third-party vendors, including Google, which use cookies to serve ads based on prior visits to our website. You can opt out of personalized advertising by visiting Ads Settings.',
        '3. Analytics: We use anonymous analytics to improve site performance. No personally identifiable information is tracked.',
      ],
      termsTitle: 'Terms of Service',
      termsContent: [
        'By using HiResume, you agree to these terms.',
        '1. Usage: This tool is free to use for personal and commercial resume creation.',
        '2. Liability: HiResume is provided "as is". We are not responsible for any lost data or errors in generated documents.',
        '3. Content: You retain full ownership of the content you create.',
      ],
      faqTitle: 'Frequently Asked Questions',
      faqContent: [
        { q: 'Is it really free?', a: 'Yes, HiResume is 100% free and supported by non-intrusive ads.' },
        { q: 'Where is my data stored?', a: 'Your data is stored in your browser\'s local storage. If you clear your cache, you may lose your data. We recommend exporting the JSON backup.' },
        { q: 'Can I import my old resume?', a: 'Currently, you can only import the JSON backup file generated by this tool.' },
      ],
      contactTitle: 'Contact Us',
      contactDesc: 'Have questions or feedback? Email us at abdellahmadinadz@gmail.com',
    },
    steps: {
      personal: 'Personal Info',
      experience: 'Experience',
      education: 'Education',
      skills: 'Skills',
      preview: 'Preview',
    },
    actions: {
      next: 'Next Step',
      back: 'Back',
      add: 'Add Item',
      remove: 'Remove',
      downloadPdf: 'Save as PDF',
      downloadLatex: 'Export LaTeX',
      downloadJson: 'Download Word (DOCX)',
      reset: 'Reset All',
      changeTemplate: 'Change Template',
    },
    labels: {
      fullName: 'Full Name',
      email: 'Email Address',
      phone: 'Phone Number',
      location: 'City, Country',
      website: 'LinkedIn / Portfolio URL',
      jobTitle: 'Professional Title',
      summary: 'Professional Summary',
      company: 'Company Name',
      position: 'Job Title',
      school: 'School / University',
      degree: 'Degree / Field of Study',
      startDate: 'Start Date',
      endDate: 'End Date',
      present: 'Present',
      description: 'Description',
      skillName: 'Skill',
    },
    placeholders: {
      summary: 'Experienced professional with a proven track record in...',
      description: '• Led a team of 5 developers...\n• Increased performance by 20%...',
    },
    headings: {
      experience: 'Work Experience',
      education: 'Education',
      skills: 'Skills',
      contact: 'Contact',
    },
  },
  fr: {
    metaTitle: 'Créateur de CV Gratuit en Ligne | Sans Inscription, Privé & ATS',
    metaDesc: 'Créez un CV professionnel compatible ATS en quelques minutes. 100% gratuit, sans compte, sécurisé. Téléchargez en PDF, Word ou LaTeX.',
    metaKeywords: 'créateur cv gratuit, cv en ligne, sans inscription, modèle cv pdf, cv compatible ats, curriculum vitae word, faire son cv gratuit',
    nav: {
      brand: 'HiResume',
      create: 'Éditer CV',
      preview: 'Aperçu',
      features: 'Atouts',
      builder: 'Créer mon CV',
    },
    landing: {
      heroTitle: 'Le seul générateur de CV qui respecte votre vie privée',
      heroSubtitle: 'Créez un CV gagnant en quelques minutes. Aucun compte requis. Pas de frais cachés. Vos données ne quittent jamais votre navigateur.',
      cta: 'Créer mon CV',
      ctaSecondary: 'Voir les modèles',
      trustedBy: 'Utilisé par des candidats recrutés chez',
      stats: { users: '100% Gratuit', downloads: 'PDF & LaTeX', cost: 'Confidentiel' },
      howItWorksTitle: 'Comment créer un CV en 3 étapes',
      howItWorksSteps: [
        { title: 'Choisissez un modèle', desc: 'Sélectionnez parmi 6+ modèles professionnels optimisés pour les recruteurs.' },
        { title: 'Entrez vos détails', desc: 'Remplissez votre expérience et vos compétences. Tout est sauvegardé automatiquement.' },
        { title: 'Téléchargez et postulez', desc: 'Exportez instantanément en PDF haute qualité, Word, ou en code LaTeX.' }
      ],
      templatesTitle: 'Modèles professionnels pour toute carrière',
      templatesDesc: 'Propres, modernes et conçus pour passer les systèmes de suivi des candidats (ATS).',
      featuresTitle: 'Pourquoi choisir HiResume ?',
      feature1Title: 'Zéro collecte de données',
      feature1Desc: 'Contrairement aux autres, vos informations personnelles sont stockées localement dans votre navigateur. Elles n\'atteignent jamais nos serveurs.',
      feature2Title: '100% Compatible ATS',
      feature2Desc: 'Nos modèles sont codés pour être facilement lus par les logiciels de recrutement, garantissant que votre CV arrive à un humain.',
      feature3Title: 'Exports Gratuits',
      feature3Desc: 'La plupart des outils font payer les téléchargements. Nous vous offrons le PDF, le DOCX et le code source LaTeX gratuitement.',
      seoTitle: 'Pourquoi un CV sans inscription ?',
      seoContent: 'Sur le marché du travail actuel, la rapidité et la confidentialité sont essentielles. Les créateurs de CV traditionnels vous obligent à créer des comptes et gardent souvent vos données en otage derrière un mur payant. HiResume change cela. Nous offrons une expérience entièrement côté client. Que vous ayez besoin d\'un CV étudiant ou d\'un CV cadre, notre outil s\'adapte sans vous suivre.',
      faqTitle: 'Questions Fréquentes',
      faqItems: [
        { q: 'Est-ce vraiment gratuit ?', a: 'Oui. Nous nous finançons via des publicités non intrusives pour ne jamais avoir à vendre vos données.' },
        { q: 'Mon employeur verra-t-il mon CV ?', a: 'Non. Vos données sont stockées uniquement sur votre appareil.' },
        { q: 'Qu\'est-ce qu\'un CV compatible ATS ?', a: 'Les ATS sont des robots qui lisent les CV avant les humains. Nos modèles utilisent un formatage standard lisible par ces robots.' }
      ]
    },
    footer: {
      copyright: '© 2026 HiResume. Tous droits réservés.',
      privacy: 'Politique de Confidentialité',
      terms: 'Conditions d\'Utilisation',
      contact: 'Contact',
      faq: 'FAQ',
      disclaimer: 'Soutenu par des publicités respectueuses de la vie privée.',
    },
    legal: {
      privacyTitle: 'Politique de Confidentialité',
      privacyContent: [
        'Chez HiResume, votre vie privée est notre priorité.',
        '1. Collecte de données : Nous ne collectons, ne stockons ni ne transmettons vos données personnelles. Tout reste dans le stockage local de votre navigateur.',
        '2. Cookies & Publicité : Nous utilisons des fournisseurs tiers, dont Google, qui utilisent des cookies pour diffuser des annonces.',
        '3. Analytique : Nous utilisons des analyses anonymes pour améliorer les performances.',
      ],
      termsTitle: 'Conditions d\'Utilisation',
      termsContent: [
        'En utilisant HiResume, vous acceptez ces conditions.',
        '1. Utilisation : Cet outil est gratuit pour un usage personnel et commercial.',
        '2. Responsabilité : HiResume est fourni "tel quel". Nous ne sommes pas responsables des pertes de données.',
        '3. Contenu : Vous conservez la propriété totale du contenu que vous créez.',
      ],
      faqTitle: 'Foire Aux Questions',
      faqContent: [
        { q: 'Est-ce vraiment gratuit ?', a: 'Oui, HiResume est 100% gratuit, soutenu par des publicités non intrusives.' },
        { q: 'Où sont mes données ?', a: 'Vos données sont stockées dans votre navigateur. Pensez à exporter le fichier JSON pour les sauvegarder.' },
        { q: 'Puis-je importer mon ancien CV ?', a: 'Actuellement, vous ne pouvez importer que le fichier de sauvegarde JSON généré par cet outil.' },
      ],
      contactTitle: 'Contactez-nous',
      contactDesc: 'Des questions ou des retours ? Écrivez-nous à abdellahmadinadz@gmail.com',
    },
    steps: {
      personal: 'Infos Personnelles',
      experience: 'Expérience',
      education: 'Formation',
      skills: 'Compétences',
      preview: 'Aperçu',
    },
    actions: {
      next: 'Suivant',
      back: 'Retour',
      add: 'Ajouter',
      remove: 'Supprimer',
      downloadPdf: 'Sauver en PDF',
      downloadLatex: 'Export LaTeX',
      downloadJson: 'Télécharger Word (DOCX)',
      reset: 'Réinitialiser',
      changeTemplate: 'Changer le modèle',
    },
    labels: {
      fullName: 'Nom Complet',
      email: 'Adresse Email',
      phone: 'Téléphone',
      location: 'Ville, Pays',
      website: 'LinkedIn / Portfolio',
      jobTitle: 'Titre Professionnel',
      summary: 'Résumé Professionnel',
      company: 'Entreprise',
      position: 'Poste Occupé',
      school: 'École / Université',
      degree: 'Diplôme',
      startDate: 'Date de début',
      endDate: 'Date de fin',
      present: 'Aujourd\'hui',
      description: 'Description',
      skillName: 'Compétence',
    },
    placeholders: {
      summary: 'Professionnel expérimenté avec un historique prouvé dans...',
      description: '• Gestion d\'une équipe de 5 développeurs...\n• Augmentation de la performance de 20%...',
    },
    headings: {
      experience: 'Expérience Professionnelle',
      education: 'Formation',
      skills: 'Compétences',
      contact: 'Contact',
    },
  },
  es: {
    metaTitle: 'Creador de Currículum Gratis | Sin Registro, Privado y ATS',
    metaDesc: 'Crea un CV profesional compatible con ATS en minutos. 100% gratis, sin cuenta. Exporta a PDF, Word (DOCX) y LaTeX. Tus datos permanecen en tu dispositivo.',
    metaKeywords: 'creador curriculum gratis, hacer cv online, sin registro, plantilla cv pdf, cv compatible ats, curriculum vitae word, privacidad',
    nav: {
      brand: 'HiResume',
      create: 'Editar CV',
      preview: 'Vista Previa',
      features: 'Características',
      builder: 'Ir al Editor',
    },
    landing: {
      heroTitle: 'El Único Creador de CV Gratuito y Privado',
      heroSubtitle: 'Crea un currículum ganador en minutos. Sin cuenta. Sin seguimiento. Sin muros de pago. Tus datos nunca salen de tu navegador.',
      cta: 'Crear Mi CV',
      ctaSecondary: 'Ver Plantillas',
      trustedBy: 'Utilizado por candidatos contratados en',
      stats: { users: '100% Gratis', downloads: 'PDF y LaTeX', cost: 'Privacidad Primero' },
      howItWorksTitle: 'Cómo crear un CV en 3 pasos',
      howItWorksSteps: [
        { title: 'Elige una Plantilla', desc: 'Selecciona entre 6+ diseños profesionales y optimizados para ATS.' },
        { title: 'Ingresa tus Detalles', desc: 'Completa tu experiencia y habilidades. Todo se guarda automáticamente en tu dispositivo.' },
        { title: 'Descarga y Postula', desc: 'Exporta al instante como archivo PDF, Word o LaTeX de alta calidad.' }
      ],
      templatesTitle: 'Plantillas Profesionales para cada Carrera',
      templatesDesc: 'Limpias, modernas y diseñadas para pasar los Sistemas de Seguimiento de Candidatos (ATS).',
      featuresTitle: 'Por qué elegir HiResume',
      feature1Title: 'Cero Recolección de Datos',
      feature1Desc: 'No queremos tus datos. A diferencia de otros, tu información personal se almacena localmente en tu navegador. Nunca llega a nuestros servidores.',
      feature2Title: '100% Compatible con ATS',
      feature2Desc: 'Nuestras plantillas están codificadas para ser leídas fácilmente por el software de reclutamiento, asegurando que tu CV llegue a un humano.',
      feature3Title: 'Exportaciones Gratuitas',
      feature3Desc: 'La mayoría cobra por descargas de alta calidad. Nosotros te damos PDF, DOCX y código fuente LaTeX totalmente gratis.',
      seoTitle: '¿Por qué un Creador de CV sin registro?',
      seoContent: 'En el mercado laboral actual, la velocidad y la privacidad son esenciales. Los creadores de CV tradicionales te obligan a crear cuentas y a menudo retienen tus datos. HiResume cambia eso. Ofrecemos una experiencia completamente del lado del cliente. Ya sea que necesites un CV de estudiante o ejecutivo, nuestra herramienta se adapta a ti.',
      faqTitle: 'Preguntas Frecuentes',
      faqItems: [
        { q: '¿Es realmente gratis?', a: 'Sí. Nos financiamos con anuncios no intrusivos para no tener que cobrarte ni vender tus datos.' },
        { q: '¿Verá mi empleador mi CV?', a: 'No. Tus datos se almacenan solo en tu dispositivo específico.' },
        { q: '¿Qué es un CV compatible con ATS?', a: 'Los ATS son robots que leen los CV antes que los humanos. Nuestras plantillas usan un formato estándar legible por estos robots.' }
      ]
    },
    footer: {
      copyright: '© 2026 HiResume. Todos los derechos reservados.',
      privacy: 'Política de Privacidad',
      terms: 'Términos de Servicio',
      contact: 'Contáctanos',
      faq: 'Preguntas Frecuentes',
      disclaimer: 'Soportado por anuncios que respetan la privacidad.',
    },
    legal: {
      privacyTitle: 'Política de Privacidad',
      privacyContent: [
        'En HiResume, priorizamos tu privacidad.',
        '1. Recolección de Datos: No recolectamos, almacenamos ni transmitimos tus datos personales. Todo permanece en el almacenamiento local de tu navegador.',
        '2. Cookies y Publicidad: Usamos proveedores externos, incluido Google, que usan cookies para mostrar anuncios.',
        '3. Analítica: Usamos análisis anónimos para mejorar el rendimiento.',
      ],
      termsTitle: 'Términos de Servicio',
      termsContent: [
        'Al usar HiResume, aceptas estos términos.',
        '1. Uso: Esta herramienta es gratuita para uso personal y comercial.',
        '2. Responsabilidad: HiResume se proporciona "tal cual". No somos responsables de la pérdida de datos.',
        '3. Contenuido: Conservas la propiedad total del contenido que creas.',
      ],
      faqTitle: 'Preguntas Frecuentes',
      faqContent: [
        { q: '¿Es realmente gratis?', a: 'Sí, HiResume es 100% gratis, soportado por anuncios no intrusivos.' },
        { q: '¿Dónde se guardan mis datos?', a: 'Tus datos se guardan en el navegador. Recuerda exportar el respaldo JSON.' },
        { q: '¿Puedo importar mi viejo CV?', a: 'Actualmente, solo puedes importar el archivo de respaldo JSON generado por esta herramienta.' },
      ],
      contactTitle: 'Contáctanos',
      contactDesc: '¿Preguntas o comentarios? Escríbenos a abdellahmadinadz@gmail.com',
    },
    steps: {
      personal: 'Info Personal',
      experience: 'Experiencia',
      education: 'Educación',
      skills: 'Habilidades',
      preview: 'Vista Previa',
    },
    actions: {
      next: 'Siguiente',
      back: 'Atrás',
      add: 'Añadir Item',
      remove: 'Eliminar',
      downloadPdf: 'Guardar como PDF',
      downloadLatex: 'Exportar LaTeX',
      downloadJson: 'Descargar Word (DOCX)',
      reset: 'Reiniciar',
      changeTemplate: 'Cambiar Plantilla',
    },
    labels: {
      fullName: 'Nombre Completo',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
      location: 'Ciudad, País',
      website: 'LinkedIn / Portafolio',
      jobTitle: 'Título Profesional',
      summary: 'Resumen Profesional',
      company: 'Empresa',
      position: 'Cargo',
      school: 'Institución',
      degree: 'Título',
      startDate: 'Fecha Inicio',
      endDate: 'Fecha Fin',
      present: 'Actualidad',
      description: 'Descripción',
      skillName: 'Habilidad',
    },
    placeholders: {
      summary: 'Profesional experimentado con historial probado en...',
      description: '• Lideré un equipo de 5 desarrolladores...\n• Aumenté el rendimiento en un 20%...',
    },
    headings: {
      experience: 'Experiencia Profesional',
      education: 'Educación',
      skills: 'Habilidades',
      contact: 'Contacto',
    },
  },
};