import { ResumeData, Translation, Language } from './types';

// GLOBAL AD CONFIGURATION
export const SHOW_ADS = true;

export const INITIAL_RESUME_STATE: ResumeData = {
  templateId: 'modern',
  personalInfo: {
    fullName: '',
    email: '',
    phone: '',
    location: '',
    website: '',
    summary: '',
    title: '',
  },
  experience: [],
  projects: [],
  education: [],
  certifications: [],
  skills: [],
};

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    metaTitle: 'Free Resume Builder & ATS Checker | No Signup, Private',
    metaDesc: 'Build a professional resume or check your ATS score in minutes. 100% free, no login required. Export to PDF, Word & LaTeX. Data stays on your device.',
    metaKeywords: 'resume builder, ats resume checker, free cv maker, resume score, ats scanner, no signup',
    nav: {
      brand: 'HiResume',
      create: 'Edit Resume',
      preview: 'Preview',
      features: 'Features',
      builder: 'Builder',
      ats: 'ATS Check',
    },
    landing: {
      heroTitle: 'The Only Privacy-First Free Resume Builder',
      heroSubtitle: 'Build a job-winning resume in minutes. No account needed. No tracking. No paywalls. Your data never leaves your browser.',
      cta: 'Build My Resume',
      ctaSecondary: 'Check ATS Score',
      trustedBy: 'Used by candidates hired at top companies',
      stats: { users: '100% Free', downloads: 'PDF & LaTeX', cost: 'Privacy First' },
      howItWorksTitle: 'How to Build a Resume in 3 Steps',
      howItWorksSteps: [
        { title: 'Choose a Template', desc: 'Select from 6+ professional, ATS-optimized layouts designed for clarity.' },
        { title: 'Enter Your Details', desc: 'Fill in your experience and skills. Everything is saved automatically to your device.' },
        { title: 'Download & Apply', desc: 'Export instantly as a high-quality PDF, Word, or LaTeX file.' }
      ],
      templatesTitle: 'Professional Templates for Every Career',
      templatesDesc: 'Clean, modern, and designed to pass Applicant Tracking Systems (ATS).',
      featuresTitle: 'Why Top Candidates Choose HiResume',
      feature1Title: 'Zero Data Collection',
      feature1Desc: 'We don\'t want your data. Unlike other builders, your personal info is stored locally in your browser (LocalStorage). It never hits our servers.',
      feature2Title: '100% ATS Friendly',
      feature2Desc: 'Our templates are coded to be easily parsed by recruitment software, ensuring your resume actually reaches a human recruiter.',
      feature3Title: 'Free Exports',
      feature3Desc: 'Most builders charge for high-quality downloads. We give you standard PDF, DOCX, and source LaTeX code completely free.',
      seoTitle: 'Why Use a No-Signup Resume Builder?',
      seoContent: 'In today\'s job market, speed and privacy are essential. Traditional resume builders force you to create accounts, spam your email, and often hold your data hostage behind a paywall. HiResume changes that. We offer a completely client-side experience using Next.js technology. This means you get the speed of a web app with the security of a desktop application. Whether you need a Student CV, an Executive Resume, or a Creative Portfolio, our tool adapts to your needs without tracking your every move.',
      faqTitle: 'Frequently Asked Questions',
      faqItems: [
        { q: 'Is this resume builder truly free?', a: 'Yes. We monetize via non-intrusive ads so we never have to charge you or sell your data.' },
        { q: 'Will my employer see my resume?', a: 'No. Your data is stored only on your specific device. We cannot see, share, or sell your resume.' },
        { q: 'What is an ATS friendly resume?', a: 'ATS (Applicant Tracking Systems) are robots that read resumes before humans do. Our templates use standard formatting that these robots can easily read.' }
      ]
    },
    ats: {
      heroTitle: 'Free ATS Resume Checker',
      heroSubtitle: 'Score your resume against Applicant Tracking Systems (ATS) instantly. 100% Client-Side & Private.',
      uploadTitle: 'Upload your Resume',
      uploadDesc: 'Drop your PDF or DOCX file here to scan',
      analyzing: 'Analyzing your resume...',
      scoreTitle: 'Your ATS Score',
      scoreSubtitle: 'Based on structure, keywords, and readability',
      strengths: 'Strengths',
      improvements: 'Improvements Needed',
      breakdown: 'Score Breakdown',
      privacy: 'Your resume is analyzed locally in your browser and never uploaded.',
      reupload: 'Check Another Resume',
      categories: {
        sections: 'Section Structure',
        keywords: 'Keywords',
        formatting: 'Formatting',
        skills: 'Skills Match',
        clarity: 'Clarity & Length'
      },
      landing: {
        whyMatters: 'Why ATS Optimization Matters',
        whyMattersDesc: '75% of resumes are rejected by ATS bots before a human ever sees them. Our checker ensures your resume is machine-readable.',
        howWorks: 'How it Works',
        howWorksDesc: 'We parse your resume text locally using browser technologies and check for key sections, formatting issues, and keyword density.',
        privacyTitle: 'Privacy Guaranteed',
        privacyDesc: 'Unlike other checkers, we do not store your resume. The analysis happens right here in your browser.',
        faq: [
          { q: 'What is a good ATS score?', a: 'A score above 70 is considered good. Above 85 is excellent.' },
          { q: 'Do you save my resume?', a: 'No. The file never leaves your computer.' },
          { q: 'What file formats do you support?', a: 'We support PDF and DOCX files.' }
        ]
      }
    },
    footer: {
      copyright: '© 2026 HiResume. All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      contact: 'Contact Us',
      faq: 'FAQ',
      disclaimer: 'Supported by privacy-respecting ad placements.',
    },
    legal: {
      privacyTitle: 'Privacy Policy',
      privacyContent: [
        'At HiResume, we prioritize your privacy.',
        '1. Data Collection: We do not collect, store, or transmit your personal resume data.',
        '2. Local Processing: ATS analysis is performed client-side.'
      ],
      termsTitle: 'Terms of Service',
      termsContent: [
        'By using HiResume, you agree to these terms.',
        '1. Usage: This tool is free to use.'
      ],
      faqTitle: 'Frequently Asked Questions',
      faqContent: [],
      contactTitle: 'Contact Us',
      contactDesc: 'Email us at abdellahmadinadz@gmail.com',
    },
    steps: {
      personal: 'Personal Info',
      experience: 'Experience',
      projects: 'Projects',
      education: 'Education',
      certifications: 'Certifications',
      skills: 'Skills',
      preview: 'Preview',
    },
    actions: {
      next: 'Next Step',
      back: 'Back',
      add: 'Add Item',
      remove: 'Remove',
      downloadPdf: 'Download PDF',
      downloadLatex: 'Download LaTeX',
      downloadJson: 'Download Word',
      reset: 'Reset All',
      changeTemplate: 'Change Template',
    },
    labels: {
      fullName: 'Full Name',
      email: 'Email Address',
      phone: 'Phone Number',
      location: 'City, Country',
      website: 'LinkedIn / Portfolio URL',
      jobTitle: 'Professional Title',
      summary: 'Professional Summary',
      company: 'Company Name',
      position: 'Job Title',
      school: 'School / University',
      degree: 'Degree / Field of Study',
      startDate: 'Start Date',
      endDate: 'End Date',
      present: 'Present',
      description: 'Description',
      skillName: 'Skill',
      projectName: 'Project Name',
      projectLink: 'Project Link (Optional)',
      certificationName: 'Certification Name',
      certificationIssuer: 'Issuing Organization',
    },
    placeholders: {
      summary: 'Experienced professional...',
      description: 'Led a team...',
    },
    headings: {
      experience: 'Work Experience',
      projects: 'Projects',
      education: 'Education',
      certifications: 'Certifications & Awards',
      skills: 'Skills',
      contact: 'Contact',
    },
  },
  fr: {
    metaTitle: 'Vérificateur ATS Gratuit & Créateur de CV | Privé',
    metaDesc: 'Analysez votre CV pour les logiciels ATS ou créez-en un nouveau. 100% gratuit, sans inscription. Export PDF & Word. Données privées.',
    metaKeywords: 'générateur cv, test cv ats, score cv, analyseur cv gratuit, compatible ats',
    nav: {
      brand: 'HiResume',
      create: 'Éditer CV',
      preview: 'Aperçu',
      features: 'Atouts',
      builder: 'Créer mon CV',
      ats: 'Test ATS',
    },
    landing: {
      heroTitle: 'Le seul générateur de CV qui respecte votre vie privée',
      heroSubtitle: 'Créez un CV gagnant en quelques minutes. Aucun compte requis. Pas de frais cachés. Vos données ne quittent jamais votre navigateur.',
      cta: 'Créer mon CV',
      ctaSecondary: 'Tester mon CV (ATS)',
      trustedBy: 'Utilisé par des candidats recrutés dans de grandes entreprises',
      stats: { users: '100% Gratuit', downloads: 'PDF & Word', cost: 'Privé' },
      howItWorksTitle: 'Comment créer un CV en 3 étapes',
      howItWorksSteps: [
        { title: 'Choisir un modèle', desc: 'Sélectionnez parmi 6+ mises en page professionnelles optimisées pour les ATS.' },
        { title: 'Entrer vos détails', desc: 'Remplissez votre expérience et vos compétences. Tout est sauvegardé automatiquement.' },
        { title: 'Télécharger & Postuler', desc: 'Exportez instantanément en PDF, Word ou LaTeX de haute qualité.' }
      ],
      templatesTitle: 'Modèles professionnels pour toute carrière',
      templatesDesc: 'Propres, modernes et conçus pour passer les systèmes de suivi des candidats (ATS).',
      featuresTitle: 'Pourquoi choisir HiResume',
      feature1Title: 'Zéro Collecte de Données',
      feature1Desc: 'Nous ne voulons pas vos données. Contrairement aux autres, vos infos personnelles sont stockées localement dans votre navigateur.',
      feature2Title: '100% Compatible ATS',
      feature2Desc: 'Nos modèles sont codés pour être facilement lus par les logiciels de recrutement.',
      feature3Title: 'Exports Gratuits',
      feature3Desc: 'La plupart des générateurs facturent les téléchargements. Nous vous offrons PDF, DOCX et LaTeX gratuitement.',
      seoTitle: 'Pourquoi un générateur de CV sans inscription ?',
      seoContent: 'Dans le marché du travail actuel, la rapidité et la confidentialité sont essentielles. Les générateurs traditionnels vous obligent à créer des comptes et spammer votre email. HiResume change cela avec une expérience 100% côté client.',
      faqTitle: 'Questions Fréquentes',
      faqItems: [
        { q: 'Est-ce vraiment gratuit ?', a: 'Oui. Nous nous finançons via des publicités non intrusives.' },
        { q: 'Mon employeur verra-t-il mon CV ?', a: 'Non. Vos données sont stockées uniquement sur votre appareil.' },
        { q: 'Qu\'est-ce qu\'un CV compatible ATS ?', a: 'Les ATS sont des robots qui lisent les CV. Nos modèles utilisent un formatage standard lisible par ces robots.' }
      ]
    },
    ats: {
      heroTitle: 'Vérificateur de CV ATS Gratuit',
      heroSubtitle: 'Obtenez un score ATS instantané pour votre CV. 100% Côté Client & Privé.',
      uploadTitle: 'Téléversez votre CV',
      uploadDesc: 'Glissez votre fichier PDF ou DOCX ici',
      analyzing: 'Analyse en cours...',
      scoreTitle: 'Votre Score ATS',
      scoreSubtitle: 'Basé sur la structure, les mots-clés et la lisibilité',
      strengths: 'Points Forts',
      improvements: 'Améliorations Requises',
      breakdown: 'Détail du Score',
      privacy: 'Votre CV est analysé localement dans votre navigateur et n\'est jamais envoyé sur un serveur.',
      reupload: 'Vérifier un autre CV',
      categories: {
        sections: 'Structure',
        keywords: 'Mots-clés',
        formatting: 'Formatage',
        skills: 'Compétences',
        clarity: 'Clarté & Longueur'
      },
      landing: {
        whyMatters: 'Pourquoi l\'optimisation ATS est cruciale',
        whyMattersDesc: '75% des CV sont rejetés par les robots ATS avant qu\'un humain ne les voie.',
        howWorks: 'Comment ça marche',
        howWorksDesc: 'Nous analysons le texte de votre CV localement pour vérifier les sections clés et la densité des mots-clés.',
        privacyTitle: 'Confidentialité Garantie',
        privacyDesc: 'Contrairement aux autres vérificateurs, nous ne stockons pas votre CV.',
        faq: [
          { q: 'Qu\'est-ce qu\'un bon score ATS ?', a: 'Un score supérieur à 70 est bon. Au-dessus de 85, c\'est excellent.' },
          { q: 'Sauvegardez-vous mon CV ?', a: 'Non. Le fichier ne quitte jamais votre ordinateur.' },
          { q: 'Quels formats supportez-vous ?', a: 'Nous supportons les fichiers PDF et DOCX.' }
        ]
      }
    },
    footer: {
      copyright: '© 2026 HiResume. Tous droits réservés.',
      privacy: 'Politique de Confidentialité',
      terms: 'Conditions d\'Utilisation',
      contact: 'Contact',
      faq: 'FAQ',
      disclaimer: 'Soutenu par des publicités respectueuses de la vie privée.',
    },
    legal: {
      privacyTitle: 'Politique de Confidentialité',
      privacyContent: [
        'Chez HiResume, nous priorisons votre vie privée.',
        '1. Collecte de données : Nous ne collectons aucune donnée personnelle.',
        '2. Traitement local : L\'analyse ATS est effectuée côté client.'
      ],
      termsTitle: 'Conditions d\'Utilisation',
      termsContent: [
        'En utilisant HiResume, vous acceptez ces conditions.',
        '1. Usage : Cet outil est gratuit.'
      ],
      faqTitle: 'Questions Fréquentes',
      faqContent: [],
      contactTitle: 'Contactez-nous',
      contactDesc: 'Email : abdellahmadinadz@gmail.com',
    },
    steps: {
      personal: 'Infos Perso',
      experience: 'Expérience',
      projects: 'Projets',
      education: 'Éducation',
      certifications: 'Certifications',
      skills: 'Compétences',
      preview: 'Aperçu',
    },
    actions: {
      next: 'Suivant',
      back: 'Retour',
      add: 'Ajouter',
      remove: 'Supprimer',
      downloadPdf: 'Télécharger PDF',
      downloadLatex: 'Télécharger LaTeX',
      downloadJson: 'Télécharger Word',
      reset: 'Réinitialiser',
      changeTemplate: 'Changer Modèle',
    },
    labels: {
      fullName: 'Nom Complet',
      email: 'Email',
      phone: 'Téléphone',
      location: 'Ville, Pays',
      website: 'LinkedIn / Site Web',
      jobTitle: 'Titre Professionnel',
      summary: 'Profil Professionnel',
      company: 'Entreprise',
      position: 'Poste',
      school: 'École / Université',
      degree: 'Diplôme',
      startDate: 'Date de début',
      endDate: 'Date de fin',
      present: 'Aujourd\'hui',
      description: 'Description',
      skillName: 'Compétence',
      projectName: 'Nom du Projet',
      projectLink: 'Lien du Projet (Optionnel)',
      certificationName: 'Nom de la Certification',
      certificationIssuer: 'Organisme',
    },
    placeholders: {
      summary: 'Professionnel expérimenté...',
      description: 'A dirigé une équipe...',
    },
    headings: {
      experience: 'Expérience Professionnelle',
      projects: 'Projets',
      education: 'Formation',
      certifications: 'Certifications',
      skills: 'Compétences',
      contact: 'Contact',
    },
  },
  es: {
    metaTitle: 'Creador de Currículum Gratis & Verificador ATS | Privado',
    metaDesc: 'Cree un currículum profesional o verifique su puntuación ATS en minutos. 100% gratis, sin registro. Exportar a PDF y Word. Datos privados.',
    metaKeywords: 'creador curriculum, verificar ats, cv maker gratis, ats scanner, sin registro',
    nav: {
      brand: 'HiResume',
      create: 'Editar CV',
      preview: 'Vista Previa',
      features: 'Características',
      builder: 'Constructor',
      ats: 'Test ATS',
    },
    landing: {
      heroTitle: 'El Único Creador de CV que Respeta tu Privacidad',
      heroSubtitle: 'Construye un CV ganador en minutos. Sin cuenta. Sin rastreo. Sin muros de pago. Tus datos nunca salen de tu navegador.',
      cta: 'Crear Mi CV',
      ctaSecondary: 'Verificar Score ATS',
      trustedBy: 'Usado por candidatos contratados en grandes empresas',
      stats: { users: '100% Gratis', downloads: 'PDF & Word', cost: 'Privado' },
      howItWorksTitle: 'Cómo crear un CV en 3 pasos',
      howItWorksSteps: [
        { title: 'Elige una plantilla', desc: 'Selecciona entre 6+ diseños profesionales optimizados para ATS.' },
        { title: 'Ingresa tus detalles', desc: 'Completa tu experiencia y habilidades. Todo se guarda automáticamente.' },
        { title: 'Descargar y Aplicar', desc: 'Exporta al instante como archivo PDF, Word o LaTeX de alta calidad.' }
      ],
      templatesTitle: 'Plantillas Profesionales para Cada Carrera',
      templatesDesc: 'Limpias, modernas y diseñadas para pasar los Sistemas de Seguimiento de Candidatos (ATS).',
      featuresTitle: 'Por qué los mejores candidatos eligen HiResume',
      feature1Title: 'Cero Recolección de Datos',
      feature1Desc: 'No queremos tus datos. A diferencia de otros, tu información personal se almacena localmente en tu navegador.',
      feature2Title: '100% Amigable con ATS',
      feature2Desc: 'Nuestras plantillas están codificadas para ser leídas fácilmente por el software de reclutamiento.',
      feature3Title: 'Exportaciones Gratuitas',
      feature3Desc: 'La mayoría cobra por descargas. Te damos PDF, DOCX y código LaTeX completamente gratis.',
      seoTitle: '¿Por qué usar un creador de CV sin registro?',
      seoContent: 'En el mercado laboral actual, la velocidad y la privacidad son esenciales. Los constructores tradicionales te obligan a crear cuentas. HiResume ofrece una experiencia 100% del lado del cliente.',
      faqTitle: 'Preguntas Frecuentes',
      faqItems: [
        { q: '¿Es realmente gratis?', a: 'Sí. Nos financiamos a través de anuncios no intrusivos.' },
        { q: '¿Verá mi empleador mi CV?', a: 'No. Tus datos se almacenan solo en tu dispositivo.' },
        { q: '¿Qué es un CV amigable con ATS?', a: 'Los ATS son robots que leen currículums. Nuestras plantillas usan formato estándar legible por estos robots.' }
      ]
    },
    ats: {
      heroTitle: 'Verificador de CV ATS Gratis',
      heroSubtitle: 'Obtén una puntuación ATS instantánea para tu CV. 100% Lado Cliente & Privado.',
      uploadTitle: 'Sube tu Currículum',
      uploadDesc: 'Arrastra tu archivo PDF o DOCX aquí',
      analyzing: 'Analizando tu currículum...',
      scoreTitle: 'Tu Puntuación ATS',
      scoreSubtitle: 'Basado en estructura, palabras clave y legibilidad',
      strengths: 'Fortalezas',
      improvements: 'Mejoras Necesarias',
      breakdown: 'Desglose de Puntuación',
      privacy: 'Tu currículum se analiza localmente en tu navegador y nunca se sube.',
      reupload: 'Verificar Otro CV',
      categories: {
        sections: 'Estructura',
        keywords: 'Palabras Clave',
        formatting: 'Formato',
        skills: 'Habilidades',
        clarity: 'Claridad'
      },
      landing: {
        whyMatters: 'Por qué importa la optimización ATS',
        whyMattersDesc: 'El 75% de los CV son rechazados por robots ATS antes de que un humano los vea.',
        howWorks: 'Cómo funciona',
        howWorksDesc: 'Analizamos el texto de tu CV localmente para verificar secciones clave y densidad de palabras clave.',
        privacyTitle: 'Privacidad Garantizada',
        privacyDesc: 'A diferencia de otros, no almacenamos tu currículum.',
        faq: [
          { q: '¿Qué es una buena puntuación ATS?', a: 'Una puntuación superior a 70 es buena. Por encima de 85 es excelente.' },
          { q: '¿Guardan mi CV?', a: 'No. El archivo nunca sale de tu computadora.' },
          { q: '¿Qué formatos soportan?', a: 'Soportamos archivos PDF y DOCX.' }
        ]
      }
    },
    footer: {
      copyright: '© 2026 HiResume. Todos los derechos reservados.',
      privacy: 'Política de Privacidad',
      terms: 'Términos de Servicio',
      contact: 'Contacto',
      faq: 'FAQ',
      disclaimer: 'Apoyado por anuncios que respetan la privacidad.',
    },
    legal: {
      privacyTitle: 'Política de Privacidad',
      privacyContent: [
        'En HiResume, priorizamos tu privacidad.',
        '1. Recolección de datos: No recolectamos datos personales.',
        '2. Procesamiento local: El análisis ATS se realiza del lado del cliente.'
      ],
      termsTitle: 'Términos de Servicio',
      termsContent: [
        'Al usar HiResume, aceptas estos términos.',
        '1. Uso: Esta herramienta es gratuita.'
      ],
      faqTitle: 'Preguntas Frecuentes',
      faqContent: [],
      contactTitle: 'Contáctanos',
      contactDesc: 'Email: abdellahmadinadz@gmail.com',
    },
    steps: {
      personal: 'Info Personal',
      experience: 'Experiencia',
      projects: 'Proyectos',
      education: 'Educación',
      certifications: 'Certificaciones',
      skills: 'Habilidades',
      preview: 'Vista Previa',
    },
    actions: {
      next: 'Siguiente',
      back: 'Atrás',
      add: 'Agregar',
      remove: 'Eliminar',
      downloadPdf: 'Descargar PDF',
      downloadLatex: 'Descargar LaTeX',
      downloadJson: 'Descargar Word',
      reset: 'Reiniciar',
      changeTemplate: 'Cambiar Plantilla',
    },
    labels: {
      fullName: 'Nombre Completo',
      email: 'Email',
      phone: 'Teléfono',
      location: 'Ciudad, País',
      website: 'LinkedIn / Sitio Web',
      jobTitle: 'Título Profesional',
      summary: 'Resumen Profesional',
      company: 'Empresa',
      position: 'Cargo',
      school: 'Escuela / Universidad',
      degree: 'Título',
      startDate: 'Fecha de inicio',
      endDate: 'Fecha de fin',
      present: 'Presente',
      description: 'Descripción',
      skillName: 'Habilidad',
      projectName: 'Nombre del Proyecto',
      projectLink: 'Enlace del Proyecto (Opcional)',
      certificationName: 'Nombre de la Certificación',
      certificationIssuer: 'Organización',
    },
    placeholders: {
      summary: 'Profesional con experiencia...',
      description: 'Lideró un equipo...',
    },
    headings: {
      experience: 'Experiencia Laboral',
      projects: 'Proyectos',
      education: 'Educación',
      certifications: 'Certificaciones',
      skills: 'Habilidades',
      contact: 'Contacto',
    },
  },
};